<a href="https://colab.research.google.com/github/mdaugherity/MachineLearning2024/blob/main/class/Class_1_22_24_Intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

# PHYS 453 - Spring 2024
## Class 1-22-2024

A quick intro to python
This is **bold** and this is *italics*.

Most funly, we can do $\LaTeX$

You can do all of the math $\frac{1}{2}=\nabla \alpha^{\beta} 7 \pi $

Set up sections
# Title
## Header
### Sub header
#### sub sub header



In [2]:
x = 12
y = 3.1415
print(x,y)

# Use f-strings
print(f"The numbers are x={x} and y={y}")
print(f"The numbers are x={x} and y={y:8.3f}")
print(f"The numbers are x={x} and y={y:8.3e}")
print(f"A big number is {123876419283641:,}")


12 3.1415
The numbers are x=12 and y=3.1415
The numbers are x=12 and y=   3.142
The numbers are x=12 and y=3.142e+00
A big number is 123,876,419,283,641


In [3]:
print("We can also add tabs \t and \t new \n lines \n")

We can also add tabs 	 and 	 new 
 lines 



# LOOPS
Remember, python loops run on **LISTS**

In [4]:
for i in [0, 23.5, 'steve', 3]:
  print(i)

0
23.5
steve
3


In [5]:
for i in range(5):
  print(i)

0
1
2
3
4


# LOGIC

In [6]:
i=3
if i==0:
  print("i is zero")

In [7]:
i = 7/2
if i==3.5:
  print("THIS IS VERY BAD THING TO DO DONT DO THIS")

THIS IS VERY BAD THING TO DO DONT DO THIS


In [8]:
# DO THIS INSTEAD
if abs(i-3.5)<1e-6:
  print("I is close to 3.5")

I is close to 3.5


# NUMPY

##Making Arrays
Main ways to make an array:  
* array
* linspace
* arange
* zeros

In [9]:
x = np.array([1,2,3,4])
x

array([1, 2, 3, 4])

In [10]:
x = np.linspace(0, 10, 11)

In [11]:
x = np.arange(0, 10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [13]:
a = np.zeros( (3,2) )

## Array Shape
Pay attention to the shape (dimensions) of the array.
Use ```reshape``` to change


In [14]:
a.shape

(3, 2)

In [15]:
a = np.zeros(5)
b = np.zeros((1,5))

In [16]:
a

array([0., 0., 0., 0., 0.])

In [17]:
b

array([[0., 0., 0., 0., 0.]])

In [18]:
a.shape

(5,)

In [19]:
b.shape

(1, 5)

In [20]:
x = np.array([1,2,3,4])

In [21]:
x.shape

(4,)

In [22]:
x.reshape((4,1))

array([[1],
       [2],
       [3],
       [4]])

In [23]:
x.reshape((1,4))

array([[1, 2, 3, 4]])

Can use -1 as a wild card

In [24]:
x.reshape( (1,-1))

array([[1, 2, 3, 4]])

In [25]:
x.reshape( (-1,2))

array([[1, 2],
       [3, 4]])

In [26]:
a.shape

(5,)

In [27]:
b.shape

(1, 5)

In [28]:
a.reshape((1,-1))

array([[0., 0., 0., 0., 0.]])

In [29]:
b2 = b.reshape(-1)

In [30]:
np.reshape?

In [31]:
x = np.arange(8).reshape(4,-1)
x

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

##Indexing and Slicing Tricks

In [32]:
x[2,0]

4

In [33]:
x[2][0]

4

In [34]:
x[2]

array([4, 5])

In [35]:
x[:,1]

array([1, 3, 5, 7])

In [36]:
x[:,:]

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [37]:
y = np.arange(10)

In [38]:
y[:]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [39]:
y[1:4]

array([1, 2, 3])

In [40]:
y[:4]

array([0, 1, 2, 3])

In [41]:
y[4:]

array([4, 5, 6, 7, 8, 9])

In [42]:
y[:]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [43]:
y[-1]

9

In [44]:
y[6:-1]

array([6, 7, 8])

In [45]:
y[ y>5 ]

array([6, 7, 8, 9])

In [46]:
y [y%2==0]

array([0, 2, 4, 6, 8])

## Looping!

In [47]:
x = np.linspace(0,1,5)
for i in x:
  print(i)

0.0
0.25
0.5
0.75
1.0


In [48]:
# BAD
for i in range(len(x)):
  print(x[i])

0.0
0.25
0.5
0.75
1.0


In [49]:
for i,val in enumerate(x):
  print(i, val)

0 0.0
1 0.25
2 0.5
3 0.75
4 1.0


In [50]:
y = x**2

In [51]:
for xv, yv in zip(x,y):
  #print(xv,"\t", yv)
  print(f"{xv}\t{yv}")

0.0	0.0
0.25	0.0625
0.5	0.25
0.75	0.5625
1.0	1.0
