<a href="https://colab.research.google.com/github/mdaugherity/MachineLearning2024/blob/main/class/HW3_Neighbors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# HW3 - Won't You Be My Neighbor?

In this assignment you will write your own simplified version of a Nearest Neighbors classifier and test it out on the famous Iris dataset. The code for loading our data is below--use it without modifications.  You need to perform a few tasks to convince me that your classifier works.

In [1]:
import numpy as np
import matplotlib.pyplot as plt

from sklearn import datasets
from sklearn import neighbors

# Problem 1 - Validation on a Single Point
Bearing in mind my Golden Rule of Computing$^{TM}$:

**ALWAYS TEST YOUR CODE IN CASES WHERE YOU KNOW THE RIGHT ANSWER**

a) Find the distances from a single point to every point in X_prob1.

b) Find the closest point and classify using y_prob1

c) Make a plot

Do not use scikit-learn's classifier.  You have to do this yourself.



In [2]:
X_prob1 = np.array([[0,0],[10,10]])
y_prob1 = np.array([0,1])
p = np.array([3,4]) # point to classify

# Problem 2 - Validation on Many Points

Repeat problem 1 classifying all of the points in X_pred.  

Your code is equivalent to the ```predict``` function of a $k=1$ nearest neighbors classifier.  


In [3]:
X_pred = 10*np.random.rand(10,2)

# Problem 3 - Iris With 2 Features

Use the 2-feature Iris data below to classify X2_pred based on X2D and y.  Make a nice, proper plot.


In [4]:
data = datasets.load_iris()
#print('Features:\t',data.feature_names)

X = data.data
y = data.target

# Make a 2-feature version of X using only the first two columns
fx = 0 # feature number to plot on x axis
fy = 1 # feature number to plot on y axis
print('Features: ', data.feature_names[fx], data.feature_names[fy])

X2D = X[:,[fx,fy]]   # 2D version
print(X2D.shape)

Features:  sepal length (cm) sepal width (cm)
(150, 2)


In [5]:
# The point to predict
X2_pred = np.array([[6.5, 3.8]])    # note that this is a 2D array like X

# Problem 4 - Full Version
Finally, classify the points in X_pred using the full 4-feature data in X.  

There really isn't a way to plot this, so think of ways to justify that your code works and your answer is right.

In [6]:
# Generate new dataset to classify
means = X.mean(axis=0).reshape(1,-1)
X_pred, _ = datasets.make_blobs(n_samples=10, n_features=4, centers=means, cluster_std = 1, random_state=3  )

print('The points to classify:')
print(X_pred)

The points to classify:
[[ 5.07449698  2.82730261  4.50305627  3.17544412]
 [ 5.29797339  1.51085602  4.74036743  0.0982657 ]
 [ 4.81954819  2.34434013  4.38324497  1.03881997]
 [ 5.56594513  2.70257435  3.67525852  0.57233266]
 [ 4.65828681  2.85168343  5.24414836  1.4360496 ]
 [ 4.91954131  2.03345757  4.88197796  1.0674191 ]
 [ 6.72465138  4.7669064   3.80803364  0.79465592]
 [ 4.59921     2.43091642  2.95423391 -1.21974984]
 [ 5.79951516  2.5801153   2.44413525  2.08395571]
 [ 7.63196181  3.49384318  3.85449747 -0.66415937]]
